[package]
name = "hello"
version = "0.1.1"
authors = ["Satoshi Moriai <satoshi.moriai@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
