[package]
name = "hello"
version = "0.1.0"
authors = ["Satoshi Moriai <satoshi.moriai@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
rusty-asm = "0.2"
#bitflags = "1.0"
libc-print = { path = "../../rustydos/libc-print"}
libc = { path = "../../rustydos/libc"}

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
