[package]
name = "hello"
version = "0.2.0"
authors = ["Satoshi Moriai <satoshi.moriai@gmail.com>"]
edition = "2018"
default-run = "hello"

[dependencies]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = "s" #or "z"

[[bin]]
name = "idiv"
path = "src/idiv.rs"
