[package]
name = "hello"
version = "0.1.0"
authors = ["Satoshi Moriai <satoshi.moriai@gmail.com>"]
edition = "2018"

[dependencies]
syscall = "0.2.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
