[package]
name = "hello"
version = "0.1.0"
authors = ["Satoshi Moriai <satoshi.moriai@gmail.com>"]
edition = "2018"

[dependencies]
sc = "0.2.7"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
strip = "symbols"
